title: "HoyaGallery"
email: "hoyana1225@example.com"
description: "사진 찍는게 취미인 개발자의 전시"
baseurl: "" # 루트 경로로 설정합니다.
url: "https://hoya324.github.io" # GitHub Pages URL
github_username: Hoya324
theme: "minimal-mistakes-jekyll"
markdown: kramdown
permalink: "/:categories/:title/" # 기본 permalink 설정

# Jekyll 플러그인 설정
plugins:
  - jekyll-feed
  - jekyll-sitemap # 사이트맵 플러그인 추가 가능

# 파일 경로 설정
collections_dir: _collections
data_dir: _data
layouts_dir: _layouts
includes_dir: _includes
include:
  - assets
