name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 트리거
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3  # Gemfile.lock에 정의된 Ruby 버전
          bundler-cache: true  # Bundler 캐시를 활성화하여 빌드 속도 향상

      - name: Install dependencies
        run: |
          gem install bundler:2.5.22  # 사용 중인 Bundler 버전 명시적으로 설치
          bundle install  # 필요한 gem 설치

      - name: Build the Jekyll site
        run: bundle exec jekyll build -d ./_site  # Jekyll 사이트 빌드

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
