name: Jekyll Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # Attempt Ruby 3.3; may need to fall back if not fully supported
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build
